export const CREDIT_INQUIRY_AUDIT_ACTIONS = {
  CREATED: 'CREDIT_INQUIRY_CREATED',
  FINANCIAL_INSTITUTION_CREATED: 'FINANCIAL_INSTITUTION_CREATED',
} as const;

export const IDEMPOTENCY_KEY_PATTERN = /^[A-Za-z0-9._:-]{8,120}$/;
