export const USER_AUDIT_ACTIONS = {
  CREATED: 'USER_CREATED',
  ACCESS_UPDATED: 'USER_ACCESS_UPDATED',
  STATUS_UPDATED: 'USER_STATUS_UPDATED',
  TEMPORARY_PASSWORD_REISSUED: 'USER_TEMPORARY_PASSWORD_REISSUED',
  TEMPORARY_PASSWORD_EMAIL_SENT: 'USER_TEMPORARY_PASSWORD_EMAIL_SENT',
  TEMPORARY_PASSWORD_EMAIL_FAILED: 'USER_TEMPORARY_PASSWORD_EMAIL_FAILED',
} as const;
