export const JWT_ISSUER = 'luma-motos-api';
export const JWT_AUDIENCE = 'luma-motos-web';

export const ROLE_CODES = {
  VENDEDOR: 'VENDEDOR',
  ADMINISTRATIVA: 'ADMINISTRATIVA',
  ADMINISTRADOR: 'ADMINISTRADOR',
  GERENTE: 'GERENTE',
} as const;

export type RoleCode = (typeof ROLE_CODES)[keyof typeof ROLE_CODES];

export const PERMISSION_CODES = {
  USERS_READ: 'usuarios.consultar',
  USERS_MANAGE: 'usuarios.gestionar',
  CLIENTS_READ: 'clientes.consultar',
  CLIENTS_MANAGE: 'clientes.gestionar',
  CREDIT_INQUIRIES_READ: 'consultas_crediticias.consultar',
  CREDIT_INQUIRIES_VERIFY: 'consultas_crediticias.verificar',
  CREDIT_INQUIRIES_CREATE: 'consultas_crediticias.registrar',
  FINANCIAL_INSTITUTIONS_MANAGE: 'financieras.gestionar',
  CATALOG_READ: 'catalogo.consultar',
  CATALOG_MANAGE: 'catalogo.gestionar',
  INVENTORY_READ: 'inventario.consultar',
  INVENTORY_MANAGE: 'inventario.gestionar',
  INVENTORY_TRANSFER: 'inventario.transferir',
  SUPPLIERS_READ: 'proveedores.consultar',
  SUPPLIERS_MANAGE: 'proveedores.gestionar',
  SUPPLY_READ: 'abastecimiento.consultar',
  SUPPLY_MANAGE: 'abastecimiento.gestionar',
  SUPPLY_RECEIVE: 'abastecimiento.recibir',
  SALES_READ: 'ventas.consultar',
  SALES_MANAGE: 'ventas.gestionar',
  SALES_APPROVE: 'ventas.aprobar',
  SALES_CANCEL: 'ventas.cancelar',
  SALES_CLOSE: 'ventas.cerrar',
  STOCK_RESERVATIONS_MANAGE: 'reservas_stock.gestionar',
  PURCHASES_READ: 'compras.consultar',
  PURCHASES_MANAGE: 'compras.gestionar',
  PURCHASES_PAY: 'compras.pagar',
  PURCHASE_COSTS_READ: 'compras.costos.consultar',
  INCOMES_READ: 'ingresos.consultar',
  INCOMES_MANAGE: 'ingresos.gestionar',
  INCOMES_COLLECT: 'ingresos.cobrar',
  EXPENSES_READ: 'gastos.consultar',
  EXPENSES_MANAGE: 'gastos.gestionar',
  EXPENSES_PAY: 'gastos.pagar',
  EXPENSES_RECOVER: 'gastos.recuperar',
  CASH_READ: 'caja.consultar',
  CASH_MANAGE: 'caja.gestionar',
  CASH_TRANSFER: 'caja.transferir',
  CASH_REVERSE: 'caja.reversar',
  COMMISSIONS_READ: 'comisiones.consultar',
  COMMISSIONS_CONFIGURE: 'comisiones.configurar',
  COMMISSIONS_AGREE: 'comisiones.acordar',
  COMMISSIONS_PAY: 'comisiones.pagar',
  COMMISSIONS_HISTORY: 'comisiones.historial',
  COMMISSIONS_OWN: 'comisiones.propias',
} as const;

export const AUDIT_ACTIONS = {
  TEMPORARY_PASSWORD_CHANGE_FAILED: 'AUTH_TEMPORARY_PASSWORD_CHANGE_FAILED',
  TEMPORARY_PASSWORD_CHANGED: 'AUTH_TEMPORARY_PASSWORD_CHANGED',
  PASSWORD_CHANGE_FAILED: 'AUTH_PASSWORD_CHANGE_FAILED',
  PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  LOGIN_SUCCEEDED: 'AUTH_LOGIN_SUCCEEDED',
  LOGOUT: 'AUTH_LOGOUT',
  INITIAL_ADMIN_CREATED: 'INITIAL_ADMIN_CREATED',
} as const;
