export const JWT_ISSUER = 'luma-motos-api';
export const JWT_AUDIENCE = 'luma-motos-web';

export const ROLE_CODES = {
  VENDEDOR: 'VENDEDOR',
  ADMINISTRATIVA: 'ADMINISTRATIVA',
  ADMINISTRADOR: 'ADMINISTRADOR',
  GERENTE: 'GERENTE',
} as const;

export type RoleCode = (typeof ROLE_CODES)[keyof typeof ROLE_CODES];

export const PERMISSION_CODES = {
  USERS_READ: 'usuarios.consultar',
  USERS_MANAGE: 'usuarios.gestionar',
  CLIENTS_READ: 'clientes.consultar',
  CLIENTS_MANAGE: 'clientes.gestionar',
} as const;

export const AUDIT_ACTIONS = {
  TEMPORARY_PASSWORD_CHANGE_FAILED: 'AUTH_TEMPORARY_PASSWORD_CHANGE_FAILED',
  TEMPORARY_PASSWORD_CHANGED: 'AUTH_TEMPORARY_PASSWORD_CHANGED',
  PASSWORD_CHANGE_FAILED: 'AUTH_PASSWORD_CHANGE_FAILED',
  PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  LOGIN_SUCCEEDED: 'AUTH_LOGIN_SUCCEEDED',
  LOGOUT: 'AUTH_LOGOUT',
  INITIAL_ADMIN_CREATED: 'INITIAL_ADMIN_CREATED',
} as const;
